language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/view/cache

notifications:
  email: false

#https://api.travis-ci.org/repos/andersusilva/agendamento/cc.xml?branch=master